/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apresentacao;

import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import negocio.Mecanico;
import persistencia.MecanicoDAO;
import persistencia.IMecanicoDAO;

/**
 *
 * @author mathe
 */
public class fmMecanico extends javax.swing.JInternalFrame {

    /**
     * Creates new form fmMecanico
     */
    public fmMecanico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelImagemFundo2 = new apresentacao.PainelImagemFundo();
        jPanel1 = new javax.swing.JPanel();
        txtEndereco = new javax.swing.JTextField();
        lbTelefone = new javax.swing.JLabel();
        lbSexo = new javax.swing.JLabel();
        lbCpf = new javax.swing.JLabel();
        lbNome = new javax.swing.JLabel();
        cbSetor = new javax.swing.JComboBox<>();
        lbEspecialidade = new javax.swing.JLabel();
        lbData = new javax.swing.JLabel();
        rbMasculino = new javax.swing.JRadioButton();
        rbFeminino = new javax.swing.JRadioButton();
        txtNome = new javax.swing.JTextField();
        lbEndereco = new javax.swing.JLabel();
        lbSetor = new javax.swing.JLabel();
        lbAsData = new javax.swing.JLabel();
        lbAsNome = new javax.swing.JLabel();
        lbAsCpf = new javax.swing.JLabel();
        lbAsEndereco = new javax.swing.JLabel();
        lbAsTelefone = new javax.swing.JLabel();
        lbAsSexo = new javax.swing.JLabel();
        chBmw = new javax.swing.JCheckBox();
        chFiat = new javax.swing.JCheckBox();
        lbSalario = new javax.swing.JLabel();
        chChevrolet = new javax.swing.JCheckBox();
        chVolks = new javax.swing.JCheckBox();
        lbAsEspecialidade = new javax.swing.JLabel();
        lbAsSetor = new javax.swing.JLabel();
        lbAsSalario = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JFormattedTextField();
        txtCpf = new javax.swing.JFormattedTextField();
        txtData = new javax.swing.JFormattedTextField();
        txtSalario = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        btSairMecanico = new javax.swing.JButton();
        btNovoMecanico = new javax.swing.JButton();
        btSalvarMecanico = new javax.swing.JButton();

        javax.swing.GroupLayout painelImagemFundo2Layout = new javax.swing.GroupLayout(painelImagemFundo2);
        painelImagemFundo2.setLayout(painelImagemFundo2Layout);
        painelImagemFundo2Layout.setHorizontalGroup(
            painelImagemFundo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        painelImagemFundo2Layout.setVerticalGroup(
            painelImagemFundo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setClosable(true);
        setTitle("Cadastro de Mecânicos");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/reparacao.png"))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        lbTelefone.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lbTelefone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/ligar.png"))); // NOI18N
        lbTelefone.setText("Telefone:");

        lbSexo.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lbSexo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/genero.png"))); // NOI18N
        lbSexo.setText("Sexo:");

        lbCpf.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lbCpf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/carteira-de-identidade (1).png"))); // NOI18N
        lbCpf.setText("Cpf:");

        lbNome.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lbNome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/nome.png"))); // NOI18N
        lbNome.setText("Nome:");

        cbSetor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbSetor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Mecânica", "Elétrica", "Pintura", "Lanternagem", "Borracharia" }));
        cbSetor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSetorActionPerformed(evt);
            }
        });

        lbEspecialidade.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lbEspecialidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icon.png"))); // NOI18N
        lbEspecialidade.setText("Especialidade:");

        lbData.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lbData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/encontro.png"))); // NOI18N
        lbData.setText("Data Nascimento:");

        rbMasculino.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rbMasculino.setText("Masculino");
        rbMasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMasculinoActionPerformed(evt);
            }
        });

        rbFeminino.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rbFeminino.setText("Feminino");
        rbFeminino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFemininoActionPerformed(evt);
            }
        });

        lbEndereco.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lbEndereco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/localizacao.png"))); // NOI18N
        lbEndereco.setText("Endereço:");

        lbSetor.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lbSetor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/pessoas.png"))); // NOI18N
        lbSetor.setText("Setor:");

        lbAsData.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbAsData.setForeground(new java.awt.Color(240, 240, 240,0));
        lbAsData.setText("*");

        lbAsNome.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbAsNome.setForeground(new java.awt.Color(240, 240, 240,0));
        lbAsNome.setText("*");

        lbAsCpf.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbAsCpf.setForeground(new java.awt.Color(240, 240, 240,0));
        lbAsCpf.setText("*");

        lbAsEndereco.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbAsEndereco.setForeground(new java.awt.Color(240, 240, 240,0));
        lbAsEndereco.setText("*");

        lbAsTelefone.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbAsTelefone.setForeground(new java.awt.Color(240, 240, 240,0));
        lbAsTelefone.setText("*");

        lbAsSexo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbAsSexo.setForeground(new java.awt.Color(240, 240, 240,0));
        lbAsSexo.setText("*");

        lbSalario.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lbSalario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/negocios-e-financas.png"))); // NOI18N
        lbSalario.setText("Salário:");

        chChevrolet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chChevroletActionPerformed(evt);
            }
        });

        chVolks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chVolksActionPerformed(evt);
            }
        });

        lbAsEspecialidade.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbAsEspecialidade.setForeground(new java.awt.Color(240, 240, 240,0));
        lbAsEspecialidade.setText("*");

        lbAsSetor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbAsSetor.setForeground(new java.awt.Color(240, 240, 240,0));
        lbAsSetor.setText("*");

        lbAsSalario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbAsSalario.setForeground(new java.awt.Color(240, 240, 240,0));
        lbAsSalario.setText("*");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/carro (2).png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/transporte.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/logotipo.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/transporte (1).png"))); // NOI18N

        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataActionPerformed(evt);
            }
        });

        txtSalario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbAsNome)
                    .addComponent(lbAsData)
                    .addComponent(lbAsCpf)
                    .addComponent(lbAsSetor)
                    .addComponent(lbAsEspecialidade)
                    .addComponent(lbAsSalario)
                    .addComponent(lbAsSexo)
                    .addComponent(lbAsEndereco)
                    .addComponent(lbAsTelefone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lbEspecialidade)
                        .addGap(18, 18, 18)
                        .addComponent(chBmw)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chFiat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(chChevrolet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(chVolks)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(133, 133, 133))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbTelefone)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbEndereco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbNome)
                                    .addComponent(lbSetor))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbSetor, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbData)
                                .addGap(18, 18, 18)
                                .addComponent(txtData)
                                .addGap(177, 177, 177))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbCpf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lbSalario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSalario))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbSexo)
                                .addGap(7, 7, 7)
                                .addComponent(rbMasculino)
                                .addGap(45, 45, 45)
                                .addComponent(rbFeminino)))
                        .addContainerGap(20, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbNome)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbSetor)
                            .addComponent(lbAsSetor)
                            .addComponent(cbSetor, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lbAsNome)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbAsEspecialidade)
                        .addGap(28, 28, 28))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(chFiat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(chChevrolet, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(chVolks, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbEspecialidade)
                                    .addComponent(chBmw, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbAsSalario)
                    .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSexo)
                    .addComponent(rbMasculino)
                    .addComponent(rbFeminino)
                    .addComponent(lbAsSexo))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCpf)
                    .addComponent(lbAsCpf)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbData)
                    .addComponent(lbAsData)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbEndereco)
                        .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbAsEndereco, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTelefone)
                    .addComponent(lbAsTelefone)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(160, 160, 160))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/avatar.png"))); // NOI18N
        jLabel1.setText("Cadastro Funcionário");

        btSairMecanico.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btSairMecanico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/saida.png"))); // NOI18N
        btSairMecanico.setText("Sair");
        btSairMecanico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairMecanicoActionPerformed(evt);
            }
        });

        btNovoMecanico.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btNovoMecanico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/lixeira.png"))); // NOI18N
        btNovoMecanico.setText("Novo");
        btNovoMecanico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoMecanicoActionPerformed(evt);
            }
        });

        btSalvarMecanico.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btSalvarMecanico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/disquete.png"))); // NOI18N
        btSalvarMecanico.setText("Salvar");
        btSalvarMecanico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarMecanicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btSairMecanico)
                                .addGap(77, 77, 77)
                                .addComponent(btNovoMecanico)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btSalvarMecanico))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSairMecanico)
                    .addComponent(btNovoMecanico)
                    .addComponent(btSalvarMecanico))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbSetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSetorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSetorActionPerformed

    private void btSairMecanicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairMecanicoActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btSairMecanicoActionPerformed

    private void btNovoMecanicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoMecanicoActionPerformed
    // Limpando os Dados
    txtNome.setText("");
    txtData.setText("");
    txtCpf.setText("");
    cbSetor.selectWithKeyChar('s');
    txtTelefone.setText("");
    txtEndereco.setText("");
    txtSalario.setText("");
    chBmw.setSelected(false);
    chFiat.setSelected(false);
    chVolks.setSelected(false);
    chChevrolet.setSelected(false);
    rbFeminino.setSelected(false);
    rbMasculino.setSelected(false);
    lbNome.setForeground(Color.black);
    lbAsNome.setForeground(new Color(240, 240, 240, 0));
    lbData.setForeground(Color.black);
    lbAsData.setForeground(new Color(240, 240, 240, 0));     
    lbCpf.setForeground(Color.black);
    lbAsCpf.setForeground(new Color(240, 240, 240, 0));
    lbSexo.setForeground(Color.black);
    lbAsSexo.setForeground(new Color(240, 240, 240, 0));
    lbTelefone.setForeground(Color.black);
    lbAsTelefone.setForeground(new Color(240, 240, 240, 0));
    lbEndereco.setForeground(Color.black);
    lbAsEndereco.setForeground(new Color(240, 240, 240, 0)); 
    lbEndereco.setForeground(Color.black);
    lbAsSalario.setForeground(new Color(240, 240, 240, 0));
    lbSalario.setForeground(Color.black);
    lbSetor.setForeground(Color.black);
    lbAsSetor.setForeground(new Color(240, 240, 240, 0));
    
    
    }//GEN-LAST:event_btNovoMecanicoActionPerformed

    private void chChevroletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chChevroletActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chChevroletActionPerformed

    private void chVolksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chVolksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chVolksActionPerformed

    private void btSalvarMecanicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarMecanicoActionPerformed
        // TODO add your handling code here:

        int resposta = 0;
        int valor = 1;

        //instrucao para campo vazio
        boolean radiof;
        boolean radiom;
        radiof =  rbFeminino.isSelected();
        radiom =  rbMasculino.isSelected();

        //Verifica se o nome está vazio
        if(txtNome.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Falha ao Salvar. Campo nome vazio.");
            lbNome.setForeground(Color.red);
            lbAsNome.setForeground(Color.red);
            resposta = 1;
        }
        //Verifica se a data de nascimento está vazio
        if(txtData.getText().equals("  /  /    ")){
            JOptionPane.showMessageDialog(null, "Falha ao Salvar. Campo data de nascimento vazio.");
            lbData.setForeground(Color.red);
            lbAsData.setForeground(Color.red);
            resposta = 1;
        }
        //Verifica se o setor está vazio
        if(cbSetor.getSelectedItem().equals("Selecione")){
            JOptionPane.showMessageDialog(null, "Falha ao Salvar. Campo setor vazio.");
            lbSetor.setForeground(Color.red);
            lbAsSetor.setForeground(Color.red);
            resposta = 1;
        }
        //Verifica se o salário está vazio
        if(txtSalario.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Falha ao Salvar. Campo salário vazio.");
            lbSalario.setForeground(Color.red);
            lbAsSalario.setForeground(Color.red);
            resposta = 1;
        }
        //Verifica se o cpf está vazio
        if(txtCpf.getText().equals("   .   .   -  ")){
            JOptionPane.showMessageDialog(null, "Falha ao Salvar. Campo cpf vazio.");
            lbCpf.setForeground(Color.red);
            lbAsCpf.setForeground(Color.red);
            resposta = 1;
        }

        //Tratativa para ver ser se algum sexo foi selecionaddo
        if (radiom != true){
            resposta = 1;
            if(radiof == true){
                resposta = 0;
            }
            if(resposta == 1){
                JOptionPane.showMessageDialog(null, "Falha ao Salvar. Campo sexo masculino não selecionado");
                lbSexo.setForeground(Color.red);
                lbAsSexo.setForeground(Color.red);
            }
        }

        if (radiof != true){
            resposta = 1;
            if(radiom == true){
                resposta = 0;
            }
            if(resposta == 1){
                JOptionPane.showMessageDialog(null, "Falha ao Salvar. Campo sexo feminino não selecionado.");
                lbSexo.setForeground(Color.red);
                lbAsSexo.setForeground(Color.red);
            }
        }
        //Verifica se o telefone está vazio
        if(txtTelefone.getText().equals("(  )      -    ")){
            JOptionPane.showMessageDialog(null, "Falha ao Salvar. Campo telefone vazio.");
            lbTelefone.setForeground(Color.red);
            lbAsTelefone.setForeground(Color.red);
            resposta = 1;
        }
        //Verifica se o endereço está vazio
        if(txtEndereco.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Falha ao Salvar. Campo endereço vazio.");
            lbEndereco.setForeground(Color.red);
            lbAsEndereco.setForeground(Color.red);
            resposta = 1;
        }

        if (resposta == 0){
            valor =JOptionPane.showConfirmDialog(null, "Tem certeza que deseja salvar?","Sistema Oficina Mecânica",1);
        }

        if(valor==0){
            //Passando dados para o BD
            Mecanico mecanico = new Mecanico();
            mecanico.setNome(txtNome.getText());
            mecanico.setSetor(cbSetor.getSelectedItem().toString());

            if(chBmw.isSelected()){
                mecanico.setEspecialidade1("BMW");
            }
            if(chFiat.isSelected()){
                mecanico.setEspecialidade2("Fiat");
            }
            if(chChevrolet.isSelected()){
                mecanico.setEspecialidade3("Chevrolet");
            }
            if(chVolks.isSelected()){
                mecanico.setEspecialidade4("Volkswagen");
            }

            mecanico.setCpf(txtTelefone.getText());
            mecanico.setSalario("R$" + txtSalario.getText());

            try{

                SimpleDateFormat data = new SimpleDateFormat("dd/MM/yyyy");
                Calendar cal = Calendar.getInstance();
                cal.setTime(data.parse(txtData.getText()));
                mecanico.setData_nascimento(cal);

            }   catch(ParseException e){

                System.out.println(e);
            }
            if(rbMasculino.isSelected())
            mecanico.setSexo("M");
            else if(rbFeminino.isSelected())
            mecanico.setSexo("F");

            mecanico.setEndereco(txtEndereco.getText());
            mecanico.setTelefone(txtTelefone.getText());

            IMecanicoDAO dao = new MecanicoDAO();
            dao.adiciona(mecanico);
            JOptionPane.showMessageDialog(null, "Os dados foram gravados.");
            //Colocando as cores normais para casos de erro
            lbNome.setForeground(Color.black);
            lbAsNome.setForeground(new Color(240, 240, 240, 0));
            lbData.setForeground(Color.black);
            lbAsData.setForeground(new Color(240, 240, 240, 0));
            lbCpf.setForeground(Color.black);
            lbAsCpf.setForeground(new Color(240, 240, 240, 0));
            lbSexo.setForeground(Color.black);
            lbAsSexo.setForeground(new Color(240, 240, 240, 0));
            lbTelefone.setForeground(Color.black);
            lbAsTelefone.setForeground(new Color(240, 240, 240, 0));
            lbEndereco.setForeground(Color.black);
            lbAsEndereco.setForeground(new Color(240, 240, 240, 0));
        }
    }//GEN-LAST:event_btSalvarMecanicoActionPerformed

    private void txtDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataActionPerformed

    private void rbMasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMasculinoActionPerformed
        // TODO add your handling code here:
        rbFeminino.setSelected(false);
    }//GEN-LAST:event_rbMasculinoActionPerformed

    private void rbFemininoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFemininoActionPerformed
        // TODO add your handling code here:
        rbMasculino.setSelected(false);
    }//GEN-LAST:event_rbFemininoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btNovoMecanico;
    private javax.swing.JButton btSairMecanico;
    private javax.swing.JButton btSalvarMecanico;
    private javax.swing.JComboBox<String> cbSetor;
    private javax.swing.JCheckBox chBmw;
    private javax.swing.JCheckBox chChevrolet;
    private javax.swing.JCheckBox chFiat;
    private javax.swing.JCheckBox chVolks;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbAsCpf;
    private javax.swing.JLabel lbAsData;
    private javax.swing.JLabel lbAsEndereco;
    private javax.swing.JLabel lbAsEspecialidade;
    private javax.swing.JLabel lbAsNome;
    private javax.swing.JLabel lbAsSalario;
    private javax.swing.JLabel lbAsSetor;
    private javax.swing.JLabel lbAsSexo;
    private javax.swing.JLabel lbAsTelefone;
    private javax.swing.JLabel lbCpf;
    private javax.swing.JLabel lbData;
    private javax.swing.JLabel lbEndereco;
    private javax.swing.JLabel lbEspecialidade;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbSalario;
    private javax.swing.JLabel lbSetor;
    private javax.swing.JLabel lbSexo;
    private javax.swing.JLabel lbTelefone;
    private apresentacao.PainelImagemFundo painelImagemFundo2;
    private javax.swing.JRadioButton rbFeminino;
    private javax.swing.JRadioButton rbMasculino;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JFormattedTextField txtData;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNome;
    private javax.swing.JFormattedTextField txtSalario;
    private javax.swing.JFormattedTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
